GET http://localhost:4000/user-api/users-data
###

GET http://localhost:4000/user-api/user/200


###
POST http://localhost:4000/user-api/create-user
Content-Type: application/json

{
  "emp_id":200,
  "emp_name":"vishnu",
  "emp_designation":"SDE",
  "emp_city":"Hyderabad",
  "emp_age":22
}

###

PUT http://localhost:4000/user-api/modify-user
Content-Type: application/json

{
  "emp_id":300,
  "emp_name":"vishnu",
  "emp_designation":"SDE",
  "emp_city":"Bangalore",
  "emp_age":22
}

###
DELETE http://localhost:4000/user-api/delete-user/200

###








###
GET http://localhost:4000/product-api/products

###
GET http://localhost:4000/product-api/product/1

###
POST http://localhost:4000/product-api/add-product
Content-Type: application/json

{
  "product_id":2,
  "product_name":"Santoor soap",
  "product_price":25,
  "product_date_of_manufactured":"2023-01-31"
}

###
PUT http://localhost:4000/product-api/update-product
Content-Type: application/json

{
  "product_id":1,
  "product_name":"Sampoo",
  "product_price":1.5,
  "product_date_of_manufactured":"2022-12-31"
}

###
DELETE http://localhost:4000/product-api/delete/2
